### ISSUE TITLE
[BUG] - Duplicates in "list_devices.py" example

### ISSUE THREAD

**Issue by MarkTheTiger** [carbonblack/carbon-black-cloud-sdk-python#144]
I am seeing this behaviour on "list_devices.py" example (Platform Section)

OS: WIndows Server 2016
Carbon Black Cloud Products: Audit & Remediation
Python Version: 3.9.1

Describe the bug :
When results are printed to screen (showing the list of the devices) it randomly duplicates an entry, but keeping the total number of devices correct, so some devices are not shown and instead other devices are duplicated.
I've included the script in a scheduled task to refresh every 10 minutes the devices list, and I noticed that duplicated devices are never the same.

**Comment by avanbrunt-cb** [comment]
@MarkTheTiger Can you provide the CLI you are using which causes the issue you have mentioned? It's possible that if you are sorting on a property that is updated when we page through the results it could be adjusting the list which would cause a Device to be outputted twice

**Comment by MarkTheTiger** [comment]
Hi @avanbrunt-cb,
I took the example "list_devices.py" and runned it directly from Atom recalling Python (using atom-python-run, without a CLI).
After that, I also launched the script via Powershell 5.1 .

**Comment by avanbrunt-cb** [comment]
Did you provide any arguments to the script?

**Comment by MarkTheTiger** [comment]
No, just ".\list_devices.py" in powershell, in atom runned pressing F5.

**Comment by avanbrunt-cb** [comment]
@MarkTheTiger I've found that the devices request applies a sort on `last_contact_time` by default so because of our current pagination if you have a few thousand devices it takes a little bit of extra time to process all of the devices. I have a workaround for now but will look into adding a `set_rows` function to allow this to be more easily configured.

The workaround is to change the line 56 to the following
```
devices = list(query._perform_query(max_rows=10000))
```

This will set the query to retrieve the max number of devices available in one request instead of paginating.

**Comment by avanbrunt-cb** [comment]
Fixed in release v1.2.1. You can now add `query.set_max_rows(10000)` to also fetch all devices in a single query instead of using the default pagination.
